server:
  port: 8080

spring:
  thymeleaf:
    cache: false

<<<<<<< HEAD
database:
  files:
    path:
      root: D:\demo-virtual-closet
      users: ${database.files.path.root}/users
      categories: ${database.files.path.root}/categories
      closet: ${database.files.path.root}/closet
      outfit: ${database.files.path.root}/outfit
=======
#Replace Spring Security default username and password
  security:
    user:
      name: user1
      password: demo
>>>>>>> myfeature
